name: tourismapp

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2

  firebase_core: ^4.2.1
  firebase_auth: ^6.5.3
  cloud_firestore: ^6.1.0

  google_sign_in: ^6.3.0
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  geocoding: ^3.0.0

  google_fonts: ^6.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2

  http: ^1.2.1
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.2.1
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/traveller.png
    - assets/images/stadthuysmelaka.jpg
    - assets/images/afamosa.jpg
    - assets/images/market.jpg
    - assets/images/map.png
    - assets/images/logo.png
    - assets/images/profile.png
    - assets/images/airport.png
    - assets/images/visiting.png
    - assets/images/badges.png
    - assets/images/reviews.png
    - assets/images/home.png
    - assets/images/planner.png
    - assets/images/hiddengems.png
    - assets/images/quest.png
    - assets/images/companion.png
    - assets/images/busker.jpg
    - assets/images/babanyonya.jpg
    - assets/images/jonkerkitchen.jpg
    - assets/images/thedailyfix.jpg
    - assets/images/atlanticnyonya.jpg
    - assets/images/dance.jpg
    - assets/images/standing.png
    - assets/images/sun.png
    - assets/images/tourist.png
    - assets/images/traffic.png
    - assets/images/weather.png
    - assets/images/bookmark.png
    - assets/images/arrow.png
    - assets/images/event.png
    - assets/images/cutlery.png

