// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEvvCvnA2IcAYrdCQjyub9NO-uNvfnCbM',
    appId: '1:116560328450:web:3caca7c52b3dc380fd341b',
    messagingSenderId: '116560328450',
    projectId: 'questmy-56755',
    authDomain: 'questmy-56755.firebaseapp.com',
    storageBucket: 'questmy-56755.firebasestorage.app',
    measurementId: 'G-9HJE5JBJBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5T28xUKcGVvqJXPZQ93463Ada0ta6gA',
    appId: '1:116560328450:android:c9e57b50b20df8ebfd341b',
    messagingSenderId: '116560328450',
    projectId: 'questmy-56755',
    storageBucket: 'questmy-56755.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf_MphkJv9VXzfO8GO4BePdabdT-1hdFQ',
    appId: '1:116560328450:ios:91bdf67ee5114d6bfd341b',
    messagingSenderId: '116560328450',
    projectId: 'questmy-56755',
    storageBucket: 'questmy-56755.firebasestorage.app',
    iosClientId:
        '116560328450-vfludutokdlq7fqeelph3mtik770vd3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf_MphkJv9VXzfO8GO4BePdabdT-1hdFQ',
    appId: '1:116560328450:ios:91bdf67ee5114d6bfd341b',
    messagingSenderId: '116560328450',
    projectId: 'questmy-56755',
    storageBucket: 'questmy-56755.firebasestorage.app',
    iosClientId:
        '116560328450-vfludutokdlq7fqeelph3mtik770vd3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEvvCvnA2IcAYrdCQjyub9NO-uNvfnCbM',
    appId: '1:116560328450:web:e774d2f5389b0641fd341b',
    messagingSenderId: '116560328450',
    projectId: 'questmy-56755',
    authDomain: 'questmy-56755.firebaseapp.com',
    storageBucket: 'questmy-56755.firebasestorage.app',
    measurementId: 'G-2358E3F7V4',
  );
}
